[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate && cd back && pip install -r requirements.txt"
]

[phases.build]
cmds = [". /opt/venv/bin/activate && cd back && python manage.py collectstatic --noinput"]

[start]
cmd = ". /opt/venv/bin/activate && cd back && python manage.py migrate && gunicorn config.wsgi --bind 0.0.0.0:$PORT"