[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["python -m pip install --upgrade pip setuptools wheel", "pip install -r back/requirements.txt"]

[phases.build]
cmds = ["cd back && python manage.py collectstatic --noinput"]

[start]
cmd = "cd back && python manage.py migrate && gunicorn config.wsgi --bind 0.0.0.0:$PORT"
