[build]
builder = "NIXPACKS"
buildCommand = "cd back && pip install -r requirements.txt && python manage.py collectstatic --noinput"

[deploy]
startCommand = "cd back && python manage.py migrate --noinput && python manage.py seed_data && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
